# Generated by Django 4.0.6 on 2022-08-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Course_Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Задание')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.course')),
            ],
            options={
                'verbose_name': 'Лабораторная работа курса',
                'verbose_name_plural': 'Лабораторные работы курса',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество')),
                ('course', models.PositiveSmallIntegerField(verbose_name='Курс')),
                ('group', models.CharField(max_length=10, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Student_Lab_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(blank=True, null=True, upload_to='', verbose_name='Отчет')),
                ('issued', models.DateTimeField(auto_now_add=True, verbose_name='Выдана')),
                ('completed', models.DateTimeField(blank=True, null=True, verbose_name='Выполнена')),
                ('changed', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменена')),
                ('course_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.course_lab')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.student')),
            ],
            options={
                'verbose_name': 'Лабораторная работа студента',
                'verbose_name_plural': 'Лабораторные работы студентов',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='labs',
            field=models.ManyToManyField(through='mysite.Student_Lab_Course', to='mysite.course_lab'),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество')),
                ('courses', models.ManyToManyField(to='mysite.course')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
