# Generated by Django 4.0.6 on 2022-08-07 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0004_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Отчество'),
        ),
    ]
