# Generated by Django 4.0.6 on 2022-08-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_lab_course',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='student_lab_course',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Оценка'),
        ),
    ]
