# Generated by Django 3.1.5 on 2021-01-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='course_lab',
            options={'verbose_name': 'Лабораторная работа курса', 'verbose_name_plural': 'Лабораторные работы курса'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='student_lab_course',
            options={'verbose_name': 'Лабораторная работа студента', 'verbose_name_plural': 'Лабораторные работы студентов'},
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course_lab',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course_lab',
            name='task',
            field=models.TextField(verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.PositiveSmallIntegerField(verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=10, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=25, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student_lab_course',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменена'),
        ),
        migrations.AlterField(
            model_name='student_lab_course',
            name='completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выполнена'),
        ),
        migrations.AlterField(
            model_name='student_lab_course',
            name='issued',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Выдана'),
        ),
        migrations.AlterField(
            model_name='student_lab_course',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Отчет'),
        ),
    ]
